# Generated by Django 3.0.2 on 2020-01-08 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NestedComment',
        ),
    ]
